CREATE EXTENSION IF NOT EXISTS pgaudit;

CREATE ROLE migration_owner
  NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
COMMENT ON ROLE migration_owner IS
  'Offline schema owner; bootstrap-superuser assumption is break-glass and can alter schema protections';

CREATE ROLE gateway_runtime
  LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
CREATE ROLE audit_reader
  LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
CREATE ROLE security_admin
  LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;

DO $$
DECLARE
  database_name TEXT;
BEGIN
  FOR database_name IN SELECT datname FROM pg_database LOOP
    EXECUTE format('REVOKE CONNECT, TEMPORARY ON DATABASE %I FROM PUBLIC', database_name);
  END LOOP;
  EXECUTE format(
    'GRANT CONNECT ON DATABASE %I TO gateway_runtime, audit_reader, security_admin',
    current_database()
  );
END;
$$;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO gateway_runtime, audit_reader, security_admin;
GRANT CREATE, USAGE ON SCHEMA public TO migration_owner;

ALTER DEFAULT PRIVILEGES FOR ROLE migration_owner
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE migration_owner
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE migration_owner
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
